namespace game;

table TestEcho
{
	type: uint16;
	data: string (required);
}

table UserLoginReq
{
	type: uint16;
	user_name: string;
}

table UserLoginAck
{
	type: uint16;
	user_name: string;
	user_no: int32;
}

table UserLogoutReq
{
	type: uint16;
	user_no: int32;
}

table UserLogoutAck
{
	type: uint16;
	user_no: int32;
}

table Nak
{
	type: uint16;
	req_type: uint16;
	error_code: uint16;
}

struct Vec3
{
	x: float;
	y: float;
	z: float;
}

table PcCreateReq
{
	type: uint16;
	pc_name: string;
	pc_type: uint8;
}

table PcCreateAck
{
	type: uint16;
	pc_no: int64;
	pc_name: string;
	pc_type: uint8;
}

table PcSelectReq
{
	type: uint16;
	pc_no: int64;
}

table PcSelectAck
{
	type: uint16;
	object_id: uint64;
	pc_no: int64;
	pc_name: string;
	pc_type: uint8;
	level: int32;
	exp: int64;
	hp: int32;
	mp: int32;
	pos: Vec3;
}

table PcSummary
{
	pc_no: int64;
	pc_name: string;
	pc_type: uint8;
	level: int32;
}

table PcListNotify
{
	type: uint16;
	pc_list: [PcSummary];
}
