// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_COMMON_MYGAME_H_
#define FLATBUFFERS_GENERATED_COMMON_MYGAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");


namespace MyGame {

enum class sql_type : uint8_t {
  info = 0,
  game = 1,
  MIN = info,
  MAX = game
};

inline const sql_type (&EnumValuessql_type())[2] {
  static const sql_type values[] = {
    sql_type::info,
    sql_type::game
  };
  return values;
}

inline const char * const *EnumNamessql_type() {
  static const char * const names[3] = {
    "info",
    "game",
    nullptr
  };
  return names;
}

inline const char *EnumNamesql_type(sql_type e) {
  if (::flatbuffers::IsOutRange(e, sql_type::info, sql_type::game)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamessql_type()[index];
}

}  // namespace MyGame

#endif  // FLATBUFFERS_GENERATED_COMMON_MYGAME_H_
