// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUMERROR_ERROR_H_
#define FLATBUFFERS_GENERATED_ENUMERROR_ERROR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");


namespace error {

enum class code : uint16_t {
  ok = 0,
  sql_fail = 1,
  sql_stmt_invalid = 2,
  file_open_fail = 3,
  object_acquire_fail = 4,
  session_invalid = 5,
  user_login_fail = 6,
  user_logout_fail = 7,
  user_not_exist = 8,
  user_already_login = 9,
  user_name_invalid = 10,
  object_spawn_fail = 11,
  object_despawn_fail = 12,
  pc_create_fail = 13,
  pc_name_invalid = 14,
  pc_type_invalid = 15,
  pc_not_exist = 16,
  pc_already_selected = 17,
  pc_name_duplicate = 18,
  pc_already_in_game = 19,
  map_load_fail = 20,
  map_not_exist = 21,
  MIN = ok,
  MAX = map_not_exist
};

inline const code (&EnumValuescode())[22] {
  static const code values[] = {
    code::ok,
    code::sql_fail,
    code::sql_stmt_invalid,
    code::file_open_fail,
    code::object_acquire_fail,
    code::session_invalid,
    code::user_login_fail,
    code::user_logout_fail,
    code::user_not_exist,
    code::user_already_login,
    code::user_name_invalid,
    code::object_spawn_fail,
    code::object_despawn_fail,
    code::pc_create_fail,
    code::pc_name_invalid,
    code::pc_type_invalid,
    code::pc_not_exist,
    code::pc_already_selected,
    code::pc_name_duplicate,
    code::pc_already_in_game,
    code::map_load_fail,
    code::map_not_exist
  };
  return values;
}

inline const char * const *EnumNamescode() {
  static const char * const names[23] = {
    "ok",
    "sql_fail",
    "sql_stmt_invalid",
    "file_open_fail",
    "object_acquire_fail",
    "session_invalid",
    "user_login_fail",
    "user_logout_fail",
    "user_not_exist",
    "user_already_login",
    "user_name_invalid",
    "object_spawn_fail",
    "object_despawn_fail",
    "pc_create_fail",
    "pc_name_invalid",
    "pc_type_invalid",
    "pc_not_exist",
    "pc_already_selected",
    "pc_name_duplicate",
    "pc_already_in_game",
    "map_load_fail",
    "map_not_exist",
    nullptr
  };
  return names;
}

inline const char *EnumNamecode(code e) {
  if (::flatbuffers::IsOutRange(e, code::ok, code::map_not_exist)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamescode()[index];
}

}  // namespace error

#endif  // FLATBUFFERS_GENERATED_ENUMERROR_ERROR_H_
