// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUMCOMMON_COMMON_H_
#define FLATBUFFERS_GENERATED_ENUMCOMMON_COMMON_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");


namespace common {

enum class sql_type : uint8_t {
  info = 0,
  game = 1,
  MIN = info,
  MAX = game
};

inline const sql_type (&EnumValuessql_type())[2] {
  static const sql_type values[] = {
    sql_type::info,
    sql_type::game
  };
  return values;
}

inline const char * const *EnumNamessql_type() {
  static const char * const names[3] = {
    "info",
    "game",
    nullptr
  };
  return names;
}

inline const char *EnumNamesql_type(sql_type e) {
  if (::flatbuffers::IsOutRange(e, sql_type::info, sql_type::game)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamessql_type()[index];
}

enum class object_type : uint8_t {
  none = 0,
  pc = 1,
  npc = 2,
  monster = 3,
  drop_item = 4,
  teleport = 5,
  MIN = none,
  MAX = teleport
};

inline const object_type (&EnumValuesobject_type())[6] {
  static const object_type values[] = {
    object_type::none,
    object_type::pc,
    object_type::npc,
    object_type::monster,
    object_type::drop_item,
    object_type::teleport
  };
  return values;
}

inline const char * const *EnumNamesobject_type() {
  static const char * const names[7] = {
    "none",
    "pc",
    "npc",
    "monster",
    "drop_item",
    "teleport",
    nullptr
  };
  return names;
}

inline const char *EnumNameobject_type(object_type e) {
  if (::flatbuffers::IsOutRange(e, object_type::none, object_type::teleport)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesobject_type()[index];
}

enum class item_type : uint8_t {
  none = 0,
  stuff = 1,
  equipment = 2,
  potion = 3,
  MIN = none,
  MAX = potion
};

inline const item_type (&EnumValuesitem_type())[4] {
  static const item_type values[] = {
    item_type::none,
    item_type::stuff,
    item_type::equipment,
    item_type::potion
  };
  return values;
}

inline const char * const *EnumNamesitem_type() {
  static const char * const names[5] = {
    "none",
    "stuff",
    "equipment",
    "potion",
    nullptr
  };
  return names;
}

inline const char *EnumNameitem_type(item_type e) {
  if (::flatbuffers::IsOutRange(e, item_type::none, item_type::potion)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesitem_type()[index];
}

enum class pc_type : uint8_t {
  knight = 0,
  archer = 1,
  MIN = knight,
  MAX = archer
};

inline const pc_type (&EnumValuespc_type())[2] {
  static const pc_type values[] = {
    pc_type::knight,
    pc_type::archer
  };
  return values;
}

inline const char * const *EnumNamespc_type() {
  static const char * const names[3] = {
    "knight",
    "archer",
    nullptr
  };
  return names;
}

inline const char *EnumNamepc_type(pc_type e) {
  if (::flatbuffers::IsOutRange(e, pc_type::knight, pc_type::archer)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamespc_type()[index];
}

}  // namespace common

#endif  // FLATBUFFERS_GENERATED_ENUMCOMMON_COMMON_H_
