// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUMERROR_COMMON_H_
#define FLATBUFFERS_GENERATED_ENUMERROR_COMMON_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");


namespace common {

enum class error_code : uint16_t {
  none = 0,
  UserLoginFail = 1,
  MIN = none,
  MAX = UserLoginFail
};

inline const error_code (&EnumValueserror_code())[2] {
  static const error_code values[] = {
    error_code::none,
    error_code::UserLoginFail
  };
  return values;
}

inline const char * const *EnumNameserror_code() {
  static const char * const names[3] = {
    "none",
    "UserLoginFail",
    nullptr
  };
  return names;
}

inline const char *EnumNameerror_code(error_code e) {
  if (::flatbuffers::IsOutRange(e, error_code::none, error_code::UserLoginFail)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNameserror_code()[index];
}

}  // namespace common

#endif  // FLATBUFFERS_GENERATED_ENUMERROR_COMMON_H_
