// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUMGAME_GAME_H_
#define FLATBUFFERS_GENERATED_ENUMGAME_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");


namespace game {

enum class tr_type : uint16_t {
  TestEcho = 0,
  UserLoginReq = 1,
  UserLoginAck = 2,
  UserLogoutReq = 3,
  UserLogoutAck = 4,
  MIN = TestEcho,
  MAX = UserLogoutAck
};

inline const tr_type (&EnumValuestr_type())[5] {
  static const tr_type values[] = {
    tr_type::TestEcho,
    tr_type::UserLoginReq,
    tr_type::UserLoginAck,
    tr_type::UserLogoutReq,
    tr_type::UserLogoutAck
  };
  return values;
}

inline const char * const *EnumNamestr_type() {
  static const char * const names[6] = {
    "TestEcho",
    "UserLoginReq",
    "UserLoginAck",
    "UserLogoutReq",
    "UserLogoutAck",
    nullptr
  };
  return names;
}

inline const char *EnumNametr_type(tr_type e) {
  if (::flatbuffers::IsOutRange(e, tr_type::TestEcho, tr_type::UserLogoutAck)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamestr_type()[index];
}

}  // namespace game

#endif  // FLATBUFFERS_GENERATED_ENUMGAME_GAME_H_
