// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUMGAME_GAME_H_
#define FLATBUFFERS_GENERATED_ENUMGAME_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");


namespace Game {

enum class tr_type : uint8_t {
  TestEcho = 0,
  MIN = TestEcho,
  MAX = TestEcho
};

inline const tr_type (&EnumValuestr_type())[1] {
  static const tr_type values[] = {
    tr_type::TestEcho
  };
  return values;
}

inline const char * const *EnumNamestr_type() {
  static const char * const names[2] = {
    "TestEcho",
    nullptr
  };
  return names;
}

inline const char *EnumNametr_type(tr_type e) {
  if (::flatbuffers::IsOutRange(e, tr_type::TestEcho, tr_type::TestEcho)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamestr_type()[index];
}

}  // namespace Game

#endif  // FLATBUFFERS_GENERATED_ENUMGAME_GAME_H_
