// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUMGAME_MYGAME_H_
#define FLATBUFFERS_GENERATED_ENUMGAME_MYGAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");


namespace MyGame {

enum class type : uint8_t {
  player = 0,
  npc = 1,
  monster = 2,
  MIN = player,
  MAX = monster
};

inline const type (&EnumValuestype())[3] {
  static const type values[] = {
    type::player,
    type::npc,
    type::monster
  };
  return values;
}

inline const char * const *EnumNamestype() {
  static const char * const names[4] = {
    "player",
    "npc",
    "monster",
    nullptr
  };
  return names;
}

inline const char *EnumNametype(type e) {
  if (::flatbuffers::IsOutRange(e, type::player, type::monster)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamestype()[index];
}

}  // namespace MyGame

#endif  // FLATBUFFERS_GENERATED_ENUMGAME_MYGAME_H_
