// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENUMERROR_ERROR_H_
#define FLATBUFFERS_GENERATED_ENUMERROR_ERROR_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");


namespace error {

enum class code : uint16_t {
  none = 0,
  ObjectAcquireFail = 1,
  UserLoginFail = 2,
  UserLogoutFail = 3,
  UserNotExist = 4,
  MIN = none,
  MAX = UserNotExist
};

inline const code (&EnumValuescode())[5] {
  static const code values[] = {
    code::none,
    code::ObjectAcquireFail,
    code::UserLoginFail,
    code::UserLogoutFail,
    code::UserNotExist
  };
  return values;
}

inline const char * const *EnumNamescode() {
  static const char * const names[6] = {
    "none",
    "ObjectAcquireFail",
    "UserLoginFail",
    "UserLogoutFail",
    "UserNotExist",
    nullptr
  };
  return names;
}

inline const char *EnumNamecode(code e) {
  if (::flatbuffers::IsOutRange(e, code::none, code::UserNotExist)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamescode()[index];
}

}  // namespace error

#endif  // FLATBUFFERS_GENERATED_ENUMERROR_ERROR_H_
