// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GAME_GAME_H_
#define FLATBUFFERS_GENERATED_GAME_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace Game {

struct TestEcho;
struct TestEchoBuilder;
struct TestEchoT;

bool operator==(const TestEchoT &lhs, const TestEchoT &rhs);
bool operator!=(const TestEchoT &lhs, const TestEchoT &rhs);

struct TestEchoT : public ::flatbuffers::NativeTable {
  typedef TestEcho TableType;
  uint16_t type = 0;
  std::string data{};
};

struct TestEcho FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestEchoT NativeTableType;
  typedef TestEchoBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_DATA = 6
  };
  uint16_t type() const {
    return GetField<uint16_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::String *data() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATA);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TYPE, 2) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyString(data()) &&
           verifier.EndTable();
  }
  TestEchoT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TestEchoT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TestEcho> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TestEchoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TestEchoBuilder {
  typedef TestEcho Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint16_t type) {
    fbb_.AddElement<uint16_t>(TestEcho::VT_TYPE, type, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::String> data) {
    fbb_.AddOffset(TestEcho::VT_DATA, data);
  }
  explicit TestEchoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TestEcho> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TestEcho>(end);
    fbb_.Required(o, TestEcho::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<TestEcho> CreateTestEcho(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> data = 0) {
  TestEchoBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_type(type);
  return builder_.Finish();
}

struct TestEcho::Traits {
  using type = TestEcho;
  static auto constexpr Create = CreateTestEcho;
};

inline ::flatbuffers::Offset<TestEcho> CreateTestEchoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    const char *data = nullptr) {
  auto data__ = data ? _fbb.CreateString(data) : 0;
  return Game::CreateTestEcho(
      _fbb,
      type,
      data__);
}

::flatbuffers::Offset<TestEcho> CreateTestEcho(::flatbuffers::FlatBufferBuilder &_fbb, const TestEchoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const TestEchoT &lhs, const TestEchoT &rhs) {
  return
      (lhs.type == rhs.type) &&
      (lhs.data == rhs.data);
}

inline bool operator!=(const TestEchoT &lhs, const TestEchoT &rhs) {
    return !(lhs == rhs);
}


inline TestEchoT *TestEcho::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<TestEchoT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TestEcho::UnPackTo(TestEchoT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = data(); if (_e) _o->data = _e->str(); }
}

inline ::flatbuffers::Offset<TestEcho> CreateTestEcho(::flatbuffers::FlatBufferBuilder &_fbb, const TestEchoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TestEcho::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TestEcho> TestEcho::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TestEchoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TestEchoT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _data = _fbb.CreateString(_o->data);
  return Game::CreateTestEcho(
      _fbb,
      _type,
      _data);
}

}  // namespace Game

#endif  // FLATBUFFERS_GENERATED_GAME_GAME_H_
