// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GAME_GAME_H_
#define FLATBUFFERS_GENERATED_GAME_GAME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace game {

struct TestEcho;
struct TestEchoBuilder;
struct TestEchoT;

struct UserLoginReq;
struct UserLoginReqBuilder;
struct UserLoginReqT;

struct UserLoginAck;
struct UserLoginAckBuilder;
struct UserLoginAckT;

struct UserLogoutReq;
struct UserLogoutReqBuilder;
struct UserLogoutReqT;

struct UserLogoutAck;
struct UserLogoutAckBuilder;
struct UserLogoutAckT;

struct Nak;
struct NakBuilder;
struct NakT;

bool operator==(const TestEchoT &lhs, const TestEchoT &rhs);
bool operator!=(const TestEchoT &lhs, const TestEchoT &rhs);
bool operator==(const UserLoginReqT &lhs, const UserLoginReqT &rhs);
bool operator!=(const UserLoginReqT &lhs, const UserLoginReqT &rhs);
bool operator==(const UserLoginAckT &lhs, const UserLoginAckT &rhs);
bool operator!=(const UserLoginAckT &lhs, const UserLoginAckT &rhs);
bool operator==(const UserLogoutReqT &lhs, const UserLogoutReqT &rhs);
bool operator!=(const UserLogoutReqT &lhs, const UserLogoutReqT &rhs);
bool operator==(const UserLogoutAckT &lhs, const UserLogoutAckT &rhs);
bool operator!=(const UserLogoutAckT &lhs, const UserLogoutAckT &rhs);
bool operator==(const NakT &lhs, const NakT &rhs);
bool operator!=(const NakT &lhs, const NakT &rhs);

struct TestEchoT : public ::flatbuffers::NativeTable {
  typedef TestEcho TableType;
  uint16_t type = 0;
  std::string data{};
};

struct TestEcho FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TestEchoT NativeTableType;
  typedef TestEchoBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_DATA = 6
  };
  uint16_t type() const {
    return GetField<uint16_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::String *data() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DATA);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TYPE, 2) &&
           VerifyOffsetRequired(verifier, VT_DATA) &&
           verifier.VerifyString(data()) &&
           verifier.EndTable();
  }
  TestEchoT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(TestEchoT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<TestEcho> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TestEchoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct TestEchoBuilder {
  typedef TestEcho Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint16_t type) {
    fbb_.AddElement<uint16_t>(TestEcho::VT_TYPE, type, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::String> data) {
    fbb_.AddOffset(TestEcho::VT_DATA, data);
  }
  explicit TestEchoBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TestEcho> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TestEcho>(end);
    fbb_.Required(o, TestEcho::VT_DATA);
    return o;
  }
};

inline ::flatbuffers::Offset<TestEcho> CreateTestEcho(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> data = 0) {
  TestEchoBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_type(type);
  return builder_.Finish();
}

struct TestEcho::Traits {
  using type = TestEcho;
  static auto constexpr Create = CreateTestEcho;
};

inline ::flatbuffers::Offset<TestEcho> CreateTestEchoDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    const char *data = nullptr) {
  auto data__ = data ? _fbb.CreateString(data) : 0;
  return game::CreateTestEcho(
      _fbb,
      type,
      data__);
}

::flatbuffers::Offset<TestEcho> CreateTestEcho(::flatbuffers::FlatBufferBuilder &_fbb, const TestEchoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct UserLoginReqT : public ::flatbuffers::NativeTable {
  typedef UserLoginReq TableType;
  uint16_t type = 0;
  std::string user_name{};
};

struct UserLoginReq FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UserLoginReqT NativeTableType;
  typedef UserLoginReqBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_USER_NAME = 6
  };
  uint16_t type() const {
    return GetField<uint16_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::String *user_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_USER_NAME);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TYPE, 2) &&
           VerifyOffset(verifier, VT_USER_NAME) &&
           verifier.VerifyString(user_name()) &&
           verifier.EndTable();
  }
  UserLoginReqT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(UserLoginReqT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<UserLoginReq> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UserLoginReqT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct UserLoginReqBuilder {
  typedef UserLoginReq Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint16_t type) {
    fbb_.AddElement<uint16_t>(UserLoginReq::VT_TYPE, type, 0);
  }
  void add_user_name(::flatbuffers::Offset<::flatbuffers::String> user_name) {
    fbb_.AddOffset(UserLoginReq::VT_USER_NAME, user_name);
  }
  explicit UserLoginReqBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UserLoginReq> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UserLoginReq>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UserLoginReq> CreateUserLoginReq(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> user_name = 0) {
  UserLoginReqBuilder builder_(_fbb);
  builder_.add_user_name(user_name);
  builder_.add_type(type);
  return builder_.Finish();
}

struct UserLoginReq::Traits {
  using type = UserLoginReq;
  static auto constexpr Create = CreateUserLoginReq;
};

inline ::flatbuffers::Offset<UserLoginReq> CreateUserLoginReqDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    const char *user_name = nullptr) {
  auto user_name__ = user_name ? _fbb.CreateString(user_name) : 0;
  return game::CreateUserLoginReq(
      _fbb,
      type,
      user_name__);
}

::flatbuffers::Offset<UserLoginReq> CreateUserLoginReq(::flatbuffers::FlatBufferBuilder &_fbb, const UserLoginReqT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct UserLoginAckT : public ::flatbuffers::NativeTable {
  typedef UserLoginAck TableType;
  uint16_t type = 0;
  std::string user_name{};
  int32_t user_no = 0;
};

struct UserLoginAck FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UserLoginAckT NativeTableType;
  typedef UserLoginAckBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_USER_NAME = 6,
    VT_USER_NO = 8
  };
  uint16_t type() const {
    return GetField<uint16_t>(VT_TYPE, 0);
  }
  const ::flatbuffers::String *user_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_USER_NAME);
  }
  int32_t user_no() const {
    return GetField<int32_t>(VT_USER_NO, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TYPE, 2) &&
           VerifyOffset(verifier, VT_USER_NAME) &&
           verifier.VerifyString(user_name()) &&
           VerifyField<int32_t>(verifier, VT_USER_NO, 4) &&
           verifier.EndTable();
  }
  UserLoginAckT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(UserLoginAckT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<UserLoginAck> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UserLoginAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct UserLoginAckBuilder {
  typedef UserLoginAck Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint16_t type) {
    fbb_.AddElement<uint16_t>(UserLoginAck::VT_TYPE, type, 0);
  }
  void add_user_name(::flatbuffers::Offset<::flatbuffers::String> user_name) {
    fbb_.AddOffset(UserLoginAck::VT_USER_NAME, user_name);
  }
  void add_user_no(int32_t user_no) {
    fbb_.AddElement<int32_t>(UserLoginAck::VT_USER_NO, user_no, 0);
  }
  explicit UserLoginAckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UserLoginAck> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UserLoginAck>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UserLoginAck> CreateUserLoginAck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    ::flatbuffers::Offset<::flatbuffers::String> user_name = 0,
    int32_t user_no = 0) {
  UserLoginAckBuilder builder_(_fbb);
  builder_.add_user_no(user_no);
  builder_.add_user_name(user_name);
  builder_.add_type(type);
  return builder_.Finish();
}

struct UserLoginAck::Traits {
  using type = UserLoginAck;
  static auto constexpr Create = CreateUserLoginAck;
};

inline ::flatbuffers::Offset<UserLoginAck> CreateUserLoginAckDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    const char *user_name = nullptr,
    int32_t user_no = 0) {
  auto user_name__ = user_name ? _fbb.CreateString(user_name) : 0;
  return game::CreateUserLoginAck(
      _fbb,
      type,
      user_name__,
      user_no);
}

::flatbuffers::Offset<UserLoginAck> CreateUserLoginAck(::flatbuffers::FlatBufferBuilder &_fbb, const UserLoginAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct UserLogoutReqT : public ::flatbuffers::NativeTable {
  typedef UserLogoutReq TableType;
  uint16_t type = 0;
  int32_t user_no = 0;
};

struct UserLogoutReq FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UserLogoutReqT NativeTableType;
  typedef UserLogoutReqBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_USER_NO = 6
  };
  uint16_t type() const {
    return GetField<uint16_t>(VT_TYPE, 0);
  }
  int32_t user_no() const {
    return GetField<int32_t>(VT_USER_NO, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TYPE, 2) &&
           VerifyField<int32_t>(verifier, VT_USER_NO, 4) &&
           verifier.EndTable();
  }
  UserLogoutReqT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(UserLogoutReqT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<UserLogoutReq> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UserLogoutReqT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct UserLogoutReqBuilder {
  typedef UserLogoutReq Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint16_t type) {
    fbb_.AddElement<uint16_t>(UserLogoutReq::VT_TYPE, type, 0);
  }
  void add_user_no(int32_t user_no) {
    fbb_.AddElement<int32_t>(UserLogoutReq::VT_USER_NO, user_no, 0);
  }
  explicit UserLogoutReqBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UserLogoutReq> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UserLogoutReq>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UserLogoutReq> CreateUserLogoutReq(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    int32_t user_no = 0) {
  UserLogoutReqBuilder builder_(_fbb);
  builder_.add_user_no(user_no);
  builder_.add_type(type);
  return builder_.Finish();
}

struct UserLogoutReq::Traits {
  using type = UserLogoutReq;
  static auto constexpr Create = CreateUserLogoutReq;
};

::flatbuffers::Offset<UserLogoutReq> CreateUserLogoutReq(::flatbuffers::FlatBufferBuilder &_fbb, const UserLogoutReqT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct UserLogoutAckT : public ::flatbuffers::NativeTable {
  typedef UserLogoutAck TableType;
  uint16_t type = 0;
  int32_t user_no = 0;
};

struct UserLogoutAck FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UserLogoutAckT NativeTableType;
  typedef UserLogoutAckBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_USER_NO = 6
  };
  uint16_t type() const {
    return GetField<uint16_t>(VT_TYPE, 0);
  }
  int32_t user_no() const {
    return GetField<int32_t>(VT_USER_NO, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TYPE, 2) &&
           VerifyField<int32_t>(verifier, VT_USER_NO, 4) &&
           verifier.EndTable();
  }
  UserLogoutAckT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(UserLogoutAckT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<UserLogoutAck> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UserLogoutAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct UserLogoutAckBuilder {
  typedef UserLogoutAck Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint16_t type) {
    fbb_.AddElement<uint16_t>(UserLogoutAck::VT_TYPE, type, 0);
  }
  void add_user_no(int32_t user_no) {
    fbb_.AddElement<int32_t>(UserLogoutAck::VT_USER_NO, user_no, 0);
  }
  explicit UserLogoutAckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UserLogoutAck> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UserLogoutAck>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UserLogoutAck> CreateUserLogoutAck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    int32_t user_no = 0) {
  UserLogoutAckBuilder builder_(_fbb);
  builder_.add_user_no(user_no);
  builder_.add_type(type);
  return builder_.Finish();
}

struct UserLogoutAck::Traits {
  using type = UserLogoutAck;
  static auto constexpr Create = CreateUserLogoutAck;
};

::flatbuffers::Offset<UserLogoutAck> CreateUserLogoutAck(::flatbuffers::FlatBufferBuilder &_fbb, const UserLogoutAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct NakT : public ::flatbuffers::NativeTable {
  typedef Nak TableType;
  uint16_t type = 0;
  uint16_t req_type = 0;
  uint16_t error_code = 0;
};

struct Nak FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NakT NativeTableType;
  typedef NakBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_REQ_TYPE = 6,
    VT_ERROR_CODE = 8
  };
  uint16_t type() const {
    return GetField<uint16_t>(VT_TYPE, 0);
  }
  uint16_t req_type() const {
    return GetField<uint16_t>(VT_REQ_TYPE, 0);
  }
  uint16_t error_code() const {
    return GetField<uint16_t>(VT_ERROR_CODE, 0);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TYPE, 2) &&
           VerifyField<uint16_t>(verifier, VT_REQ_TYPE, 2) &&
           VerifyField<uint16_t>(verifier, VT_ERROR_CODE, 2) &&
           verifier.EndTable();
  }
  NakT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(NakT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Nak> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const NakT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct NakBuilder {
  typedef Nak Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(uint16_t type) {
    fbb_.AddElement<uint16_t>(Nak::VT_TYPE, type, 0);
  }
  void add_req_type(uint16_t req_type) {
    fbb_.AddElement<uint16_t>(Nak::VT_REQ_TYPE, req_type, 0);
  }
  void add_error_code(uint16_t error_code) {
    fbb_.AddElement<uint16_t>(Nak::VT_ERROR_CODE, error_code, 0);
  }
  explicit NakBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Nak> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Nak>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Nak> CreateNak(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t type = 0,
    uint16_t req_type = 0,
    uint16_t error_code = 0) {
  NakBuilder builder_(_fbb);
  builder_.add_error_code(error_code);
  builder_.add_req_type(req_type);
  builder_.add_type(type);
  return builder_.Finish();
}

struct Nak::Traits {
  using type = Nak;
  static auto constexpr Create = CreateNak;
};

::flatbuffers::Offset<Nak> CreateNak(::flatbuffers::FlatBufferBuilder &_fbb, const NakT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);


inline bool operator==(const TestEchoT &lhs, const TestEchoT &rhs) {
  return
      (lhs.type == rhs.type) &&
      (lhs.data == rhs.data);
}

inline bool operator!=(const TestEchoT &lhs, const TestEchoT &rhs) {
    return !(lhs == rhs);
}


inline TestEchoT *TestEcho::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<TestEchoT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void TestEcho::UnPackTo(TestEchoT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = data(); if (_e) _o->data = _e->str(); }
}

inline ::flatbuffers::Offset<TestEcho> CreateTestEcho(::flatbuffers::FlatBufferBuilder &_fbb, const TestEchoT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return TestEcho::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<TestEcho> TestEcho::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const TestEchoT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const TestEchoT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _data = _fbb.CreateString(_o->data);
  return game::CreateTestEcho(
      _fbb,
      _type,
      _data);
}


inline bool operator==(const UserLoginReqT &lhs, const UserLoginReqT &rhs) {
  return
      (lhs.type == rhs.type) &&
      (lhs.user_name == rhs.user_name);
}

inline bool operator!=(const UserLoginReqT &lhs, const UserLoginReqT &rhs) {
    return !(lhs == rhs);
}


inline UserLoginReqT *UserLoginReq::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<UserLoginReqT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void UserLoginReq::UnPackTo(UserLoginReqT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = user_name(); if (_e) _o->user_name = _e->str(); }
}

inline ::flatbuffers::Offset<UserLoginReq> CreateUserLoginReq(::flatbuffers::FlatBufferBuilder &_fbb, const UserLoginReqT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return UserLoginReq::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<UserLoginReq> UserLoginReq::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UserLoginReqT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const UserLoginReqT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _user_name = _o->user_name.empty() ? 0 : _fbb.CreateString(_o->user_name);
  return game::CreateUserLoginReq(
      _fbb,
      _type,
      _user_name);
}


inline bool operator==(const UserLoginAckT &lhs, const UserLoginAckT &rhs) {
  return
      (lhs.type == rhs.type) &&
      (lhs.user_name == rhs.user_name) &&
      (lhs.user_no == rhs.user_no);
}

inline bool operator!=(const UserLoginAckT &lhs, const UserLoginAckT &rhs) {
    return !(lhs == rhs);
}


inline UserLoginAckT *UserLoginAck::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<UserLoginAckT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void UserLoginAck::UnPackTo(UserLoginAckT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = user_name(); if (_e) _o->user_name = _e->str(); }
  { auto _e = user_no(); _o->user_no = _e; }
}

inline ::flatbuffers::Offset<UserLoginAck> CreateUserLoginAck(::flatbuffers::FlatBufferBuilder &_fbb, const UserLoginAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return UserLoginAck::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<UserLoginAck> UserLoginAck::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UserLoginAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const UserLoginAckT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _user_name = _o->user_name.empty() ? 0 : _fbb.CreateString(_o->user_name);
  auto _user_no = _o->user_no;
  return game::CreateUserLoginAck(
      _fbb,
      _type,
      _user_name,
      _user_no);
}


inline bool operator==(const UserLogoutReqT &lhs, const UserLogoutReqT &rhs) {
  return
      (lhs.type == rhs.type) &&
      (lhs.user_no == rhs.user_no);
}

inline bool operator!=(const UserLogoutReqT &lhs, const UserLogoutReqT &rhs) {
    return !(lhs == rhs);
}


inline UserLogoutReqT *UserLogoutReq::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<UserLogoutReqT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void UserLogoutReq::UnPackTo(UserLogoutReqT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = user_no(); _o->user_no = _e; }
}

inline ::flatbuffers::Offset<UserLogoutReq> CreateUserLogoutReq(::flatbuffers::FlatBufferBuilder &_fbb, const UserLogoutReqT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return UserLogoutReq::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<UserLogoutReq> UserLogoutReq::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UserLogoutReqT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const UserLogoutReqT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _user_no = _o->user_no;
  return game::CreateUserLogoutReq(
      _fbb,
      _type,
      _user_no);
}


inline bool operator==(const UserLogoutAckT &lhs, const UserLogoutAckT &rhs) {
  return
      (lhs.type == rhs.type) &&
      (lhs.user_no == rhs.user_no);
}

inline bool operator!=(const UserLogoutAckT &lhs, const UserLogoutAckT &rhs) {
    return !(lhs == rhs);
}


inline UserLogoutAckT *UserLogoutAck::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<UserLogoutAckT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void UserLogoutAck::UnPackTo(UserLogoutAckT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = user_no(); _o->user_no = _e; }
}

inline ::flatbuffers::Offset<UserLogoutAck> CreateUserLogoutAck(::flatbuffers::FlatBufferBuilder &_fbb, const UserLogoutAckT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return UserLogoutAck::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<UserLogoutAck> UserLogoutAck::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const UserLogoutAckT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const UserLogoutAckT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _user_no = _o->user_no;
  return game::CreateUserLogoutAck(
      _fbb,
      _type,
      _user_no);
}


inline bool operator==(const NakT &lhs, const NakT &rhs) {
  return
      (lhs.type == rhs.type) &&
      (lhs.req_type == rhs.req_type) &&
      (lhs.error_code == rhs.error_code);
}

inline bool operator!=(const NakT &lhs, const NakT &rhs) {
    return !(lhs == rhs);
}


inline NakT *Nak::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<NakT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Nak::UnPackTo(NakT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = type(); _o->type = _e; }
  { auto _e = req_type(); _o->req_type = _e; }
  { auto _e = error_code(); _o->error_code = _e; }
}

inline ::flatbuffers::Offset<Nak> CreateNak(::flatbuffers::FlatBufferBuilder &_fbb, const NakT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return Nak::Pack(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Nak> Nak::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const NakT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const NakT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _type = _o->type;
  auto _req_type = _o->req_type;
  auto _error_code = _o->error_code;
  return game::CreateNak(
      _fbb,
      _type,
      _req_type,
      _error_code);
}

}  // namespace game

#endif  // FLATBUFFERS_GENERATED_GAME_GAME_H_
